dist: trusty
os: linux
language: java

addons:
  sonarcloud:
    organization: "juliancamacho341"
    token:
      secure: "d69bdf126c0ae2db31e960532dac88d855a59957"


script:
  - ant dist
  - sonar-scanner
